### ISSUE TITLE
Monthview Scroll overflow-y

### ISSUE THREAD

**Issue by digitaldirk** [danheron/Heron.MudCalendar#185]
I think if the monthview overflow-y was set to auto instead of scroll the component would look cleaner.

Willing to do a PR
- Want the css to be set to auto
- OR make a property to set this?

In my personal project I tried to set the overflow-y to auto via a style but I was not successful - could you point to where overflow-y scroll is coming from?

Thank you

**Comment by digitaldirk** [comment]
I found I had to use `!important` and it worked for my personal project.

```css
.mud-cal-month-dropzone {
     overflow-y: auto !important;
}
```

This fix works for me, but still willing to do the PR if you deem it important enough.

Thank you

**Comment by digitaldirk** [comment]
To add a similar issue,  I am making a page where I hide all Toolbar elements from the calendar. When doing this there is whitespace leftover where the toolbar items used to be.

Fix:
```css
.mud-cal-toolbar {
     padding: 0px !important;
}
```

Should this library auto hide this padding if there are no toolbar elements?

Thank you
