### ISSUE TITLE
Disable time at week view

### ISSUE THREAD

**Issue by TobiasBCC** [danheron/Heron.MudCalendar#86]
Hey,

is tehre a way to disable (hide) the time at the week view?

**Comment by danheron** [comment]
There's no property for that but you could add the style:

```css
.mud-cal-time-cell {
  visibility: hidden;
}
```
